### ISSUE TITLE
Playground: Cursor position is incorrect

### ISSUE THREAD

**Issue by Dixin** [microsoft/TypeScript-Website#449] opened 2020-04-04 01:04 UTC
Cursor position is incorrect

![Playground](https://user-images.githubusercontent.com/1563770/78415196-0e806200-75d5-11ea-9ffd-1adb31420b16.gif)

**Repro:**
Chrome 80.0.3987.163 or Edge, go to https://www.typescriptlang.org/play/

**Code**
Any code. See screen recording.

**Expected behavior:**
Click the end of the line, or press end key, the cursor should be at the end.

**Actual behavior:**
The cursor is not at the end of the line.

**Comment by bhuppal** [comment] 2020-04-04 01:26
I already reported few minutes ago.

**Comment by orta** [comment] 2020-04-04 12:07
Cool, yeah, calling a dupe of https://github.com/microsoft/TypeScript-Website/issues/449

**Closed by orta** 2020-04-04 12:07 UTC
Labels: Playground
