### ISSUE TITLE
Playground: ctrl+left/ctrl+right to move the caret between words doesn't work in firefox

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#1950] opened 2021-07-22 23:31 UTC
same with ctrl+shift+left and ctrl+shift+right

**Comment by orta** [comment] 2021-07-23 05:17
This is an upstream monaco issue I believe - https://microsoft.github.io/monaco-editor/index.html

**Comment by Gerrit0** [comment] 2021-10-14 03:34
Duplicate of https://github.com/microsoft/TypeScript-Website/issues/1763

**Closed as completed** 2021-10-14 08:10 UTC
Labels: Playground
