### ISSUE TITLE
type assertion section refers to angular bracket syntax, but example doesn't show brackets

### ISSUE THREAD

**Issue by rattias** [microsoft/TypeScript-Website#464] opened 2020-04-05 07:38 UTC
In https://www.typescriptlang.org/docs/handbook/basic-types.html, Type Assertion section, the example shows:

```
let someValue: any = "this is a string";

let strLength: number = (someValue).length;
```
where, I believe, it should read:

```
let someValue: any = "this is a string";

let strLength: number = (<string>someValue).length;
```

**Comment by orta** [comment] 2020-04-05 12:01
Thanks - Dupe of https://github.com/microsoft/TypeScript-Website/issues/458 and https://github.com/microsoft/TypeScript-Website/issues/452

**Closed by orta** 2020-04-05 12:01 UTC
