### ISSUE TITLE
Typescript Handbook -> Basic Types -> Enum missing brackets `{`

### ISSUE THREAD

**Issue by jcelmeta14** [microsoft/TypeScript-Website#403] opened 2020-03-22 13:45 UTC
Hello!

I suspect that there are some missing brackets in the Enum Section in the TypeScript Handbook.

![missing_brackets](https://user-images.githubusercontent.com/22294784/77250965-d16ab600-6c4b-11ea-9110-d833261dbe65.png)

**Comment by orta** [comment] 2020-03-22 14:21
Thanks, dupe of #283

**Comment by jcelmeta14** [comment] 2020-03-22 15:00
Great, I am closing this issue to avoid confusion 👍.

**Closed** 2020-03-22 15:00 UTC
