### ISSUE TITLE
Docs: []

### ISSUE THREAD

**Issue by rayattack** [microsoft/TypeScript-Website#418] opened 2020-03-25 15:45 UTC
**Page URL:** https://www.typescriptlang.org/v2/docs/handbook/classes.html

**Issue:** The main side navigation (left side) and secondary side navigation (right side) scroll up with the page content making it unnecessary as you have to scroll back up to use them both to navigate. This is a huge productivity and usability pain point.

**Recommended Fix:** The main side navigation (left side) and secondary side navigation (right side) should not scroll along with the page otherwise there is no point of having it as you have to scroll back up to click to navigate to another sub heading or page.

**Browser:** Brave, Chrome

**Comment by orta** [comment] 2020-03-26 15:10
Thanks for the issue, this is a dupe of https://github.com/microsoft/TypeScript-Website/issues/336

**Closed by orta** 2020-03-26 15:10 UTC
