### ISSUE TITLE
Docs: Left Angle Brackets Not Escaped -- Code Examples Broken

### ISSUE THREAD

**Issue by sharwoodjr** [microsoft/TypeScript-Website#467] opened 2020-04-05 14:52 UTC
**Page URL:** https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

**Issue:** Left angle brackets ("<") are not properly escaped (by &lt;), causing some surrounding code to "disappear". Screenshot below showing two examples.

**Recommended Fix:** Maybe there's something more elegant, but I know that replacing "<" with "&lt;" will work.

**Browser:** All major on MacOS: Chrome, Firefox, Safari

![image](https://user-images.githubusercontent.com/12161270/78501806-70eb7680-772b-11ea-8d16-4e54daf80c67.png)

**Comment by orta** [comment] 2020-04-05 16:38
Thanks - Dupe of #458

**Closed by orta** 2020-04-05 16:38 UTC
