### ISSUE TITLE
Playground: console.log on background threads don't show up in log.

### ISSUE THREAD

**Issue by grapevinegizmos** [microsoft/TypeScript-Website#718] opened 2020-06-29 23:27 UTC
If you call an async function which writes to console.log or produces an error, the log entries and error messages don't appear in the playground log, you have to inspect (in Chrome) to find the logs.

![image](https://user-images.githubusercontent.com/8684037/86065506-a4852680-ba24-11ea-8b01-b07913977b09.png)

**Repro:**

```

class Foo {
    private async test(val?: string): Promise<string> {
        if (val == "goo") {
            throw new Error("Goo error")
        }
        return "hello world";

    }

    async tryme(s?: string) {
        return (await this.test(s))
    }
}

async function testMe() {
    console.log("start");
    let f = new Foo();
    let s = await f.tryme();
    console.log(s);
    s = await f.tryme("goo");
    console.log(s);
}

testMe();

```
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
The console should log both the message "hello world", and the error message "Goo Error"

**Actual behavior:**
None of the console output produced on the async thread is shown on the Playground console, its only on the chrome console.  The playground console should capture all console output produced by the Typescript code.

**Comment by orta** [comment] 2020-06-30 19:17
Dupe of #711 👍

**Closed by orta** 2020-06-30 19:17 UTC
Labels: Playground
