### ISSUE TITLE
result of async code isnt logged correctly in 'Logs' tab

### ISSUE THREAD

**Issue by yawgmoth1806** [microsoft/TypeScript-Website#456] opened 2020-04-04 17:47 UTC
result of async code isnt logged correctly in 'Logs' tab

![Bildschirmfoto 2020-04-04 um 19 39 40](https://user-images.githubusercontent.com/24796354/78457728-9be2b580-76ac-11ea-991b-6234d8a7062e.png)

**Expected behavior:**

should log 'b', then 'a' inside log tab (like in dev tools)

**Actual behavior:**

only logs 'b' in log tab.

System: Mac with Chrome Version 80.0.3987.163

**Comment by orta** [comment] 2020-04-04 18:32
Thanks - this is a dupe of https://github.com/microsoft/TypeScript-Website/issues/367

**Closed by orta** 2020-04-04 18:32 UTC
Labels: Playground
