### ISSUE TITLE
Migration Stories area has scrollwheels

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#271] opened 2020-02-20 01:14 UTC
![image](https://user-images.githubusercontent.com/972891/74891179-22307b80-533b-11ea-9775-ba9836406f7a.png)

**Comment by KingDarBoja** [comment] 2020-02-21 22:52
@orta this is caused by the following scss:

```scss
#index .migrations {
  overflow-x: hidden;
}
```

Should be `overflow`.

**Comment by orta** [comment] 2020-02-21 22:53
hah, I swear I did this at some point after you mentioned it - but it's still there, so I must have not

**Comment by orta** [comment] 2020-03-23 16:51
This should be fixed, pretty sure I took another stab at it and can't reproduce it

**Closed by orta** 2020-03-23 16:51 UTC
