### ISSUE TITLE
Code result doesn't show on Playground "Logs"

### ISSUE THREAD

**Issue by Aman-SS** [microsoft/TypeScript-Website#711] opened 2020-06-28 08:20 UTC
**TypeScript Version:**  3.9.2

**Search Terms:**

**Expected behavior:**

**Actual behavior:**

**Related Issues:**

**Code**
```ts
for (var i = 0; i < 10; i++) {
  setTimeout(function() { console.log(i); }, 100 * i);
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
for (var i = 0; i < 10; i++) {
    setTimeout(function () { console.log(i); }, 100 * i);
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/GYewTgBAFAbghpAlhAvBADAbgsgPBARixwGoSBKCAbwCgIIBnAUwBcAVRAWyZAFcWowXgDsAxi0QhhUSlQiipDEABsmAOmUgA5lETlsAXwA0hdOggAqHPpoGgA)

**Comment by orta** [comment] 2020-06-29 12:04
Thanks - dupe of #456

**Closed by orta** 2020-06-29 12:04 UTC
Labels: Playground
