### ISSUE TITLE
Clicking on left navigation does not work on handbook

### ISSUE THREAD

**Issue by andresdominguez** [microsoft/TypeScript-Website#379] opened 2020-03-17 15:59 UTC
I cannot use the left navigation in the handbook when I click on the elements.

1. Go to https://www.typescriptlang.org/docs/handbook/enums.html
2. Click on any of the links on the left (e.g. Handbook Reference, Tutorials)

Expected
The element opens, or it navigates

Actual
Nothing happens

<img width="805" alt="Screen Shot 2020-03-17 at 11 58 49 AM" src="https://user-images.githubusercontent.com/1692599/76875282-bdd3df80-6846-11ea-9f1c-40a10bae2bbf.png">

**Comment by rbingham** [comment] 2020-03-17 16:05
I am also seeing this issue.

**Comment by erikaadvisser** [comment] 2020-03-17 16:05
The issue is broader: if you go to the release notes, then you can only navigate within the release notes, and not get to the handbook.

(I was writing the exact same issue just as you published it)

**Comment by TimMensch** [comment] 2020-03-17 16:07
Likely the same underlying cause as #378: A bunch of missing `.js` bundles and other files.

A bad deploy, maybe?

**Comment by GMScribe** [comment] 2020-03-17 17:04
Same issue here.

**Comment by orta** [comment] 2020-03-17 17:16
Going to close this in favor of #378 - thanks peeps

**Closed by orta** 2020-03-17 17:16 UTC
