### ISSUE TITLE
Idea: Code snippet dark mode 

### ISSUE THREAD

**Issue by zunamidev** [microsoft/TypeScript-Website#1311] opened 2020-10-31 19:19 UTC
Issue Report

**Improvement Idea:** Code snippet background to dark in dark mode.

**Why:** It is logical that when I switch to the dark mode that also the code snippet background switches to a dark color don't stay white. Currently, it looks like this: 
![image](https://user-images.githubusercontent.com/44585887/97787985-db776e80-1bb5-11eb-9baf-a71140c6056c.png)
and I think it would be nice if it also has a dark color.

**Alternative ideas:**
I have no alternative idea 

Sorry, I am new to open source and never done an issue before. :D

**Comment by orta** [comment] 2020-11-01 16:01
Thanks, this is a duplicate of #342

**Closed as completed by orta** 2020-11-01 16:01 UTC
Labels: Idea
