### ISSUE TITLE
TS Playground: caret & selection display broken

### ISSUE THREAD

**Issue by Cody-G-G** [microsoft/TypeScript-Website#453] opened 2020-04-04 15:48 UTC
In the v2 site, when typing in the playground it seems that the caret is not displayed at the correct position. The more I type the more it gets "shifted", and using the mouse + left click to move the caret at a different position also places it in a different position than it is displayed. Oddly, sometimes the caret is even displayed in the middle of a letter. Selection of text also is displayed differently than what the selected text actually is (if I select a chunk of text and then hit backspace to delete, it will delete more than it was showing me as selected).

Link: https://www.typescriptlang.org/play
Browser: Chrome

**Comment by orta** [comment] 2020-04-04 18:40
I think this is probably a dupe of #448

**Comment by orta** [comment] 2020-04-05 19:04
There's some issue with using monaco and remote fonts - so I switched it back to the default font

**Closed by orta** 2020-04-05 19:04 UTC
