### ISSUE TITLE
Docs: typos in "Basic Types" and "Unions and Intersection Types"

### ISSUE THREAD

**Issue by abulyshkin** [microsoft/TypeScript-Website#458] opened 2020-04-04 20:54 UTC
I'm new in TS. I've just read the handbook and probably found a few typos.

**Page URL:** https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

In a "Mixins via Intersections" topic:

`function extendextends {}, Second extends {}>(`

**Issue:** something is messed up there

and one more

**Page URL:** https://www.typescriptlang.org/docs/handbook/basic-types.html

In a "type assertion" topic:

`let someValue: any = "this is a string";`
`let strLength: number = (someValue).length;`

**Issue:** you've probably forgotten `<string>` before someValue.

**Comment by orta** [comment] 2020-04-05 12:07
Closing as dupe of https://github.com/microsoft/TypeScript-Website/issues/452

**Closed by orta** 2020-04-05 12:07 UTC

**Comment by abulyshkin** [comment] 2020-04-05 12:13
> Closing as dupe of #452

But there is still probably something wrong in `function extendextends {}, Second extends {}>(`. no space between `extendextends` and single closing angle-bracket without opening one
